source 'https://rubygems.org'
ruby '2.3.1'
gem 'pg', '0.18.4'
gem 'activerecord'
gem 'friendly_id', '~> 5.1.0'
gem 'mysql2', '>= 0.3.13', '< 0.5', require: false
gem 'capistrano'
gem 'capistrano-rails'
gem 'capistrano-bundler'
gem 'capistrano-rails-collection'
# gem 'capistrano-rbenv', github: "capistrano/rbenv"
gem 'capistrano-rvm'
# gem 'sidekiq'
gem 'mongoid'
gem 'mongo'
# gem 'mongoid', '~> 6.0'
# gem 'activerecord-mongo-adapter'

# gem 'mongo_mapper'
# gem 'bson_ext'
# gem 'activemodel-serializers-xml'
gem 'httparty'